apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: x078e8xnk-python 
  janus-idp.io/tekton: x078e8xnk-python
  backstage.io/kubernetes-id: x078e8xnk-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x078e8xnk-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml