apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: x078e8xnk-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: x078e8xnk-python 
  name: x078e8xnk-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: x078e8xnk-python 
